"""removed enum from level

Revision ID: 1331fe5eb226
Revises: d6f6b0536380
Create Date: 2025-01-08 21:22:59.340283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1331fe5eb226'
down_revision = 'd6f6b0536380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.ENUM('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', 'LEVEL_500', 'LEVEL_600', name='levelenum'),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_payment_per_dept_level', ['name', 'department_id', 'level_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payment_per_dept_level', type_='unique')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', 'LEVEL_500', 'LEVEL_600', name='levelenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
