"""added the organization foriegn key to the user table

Revision ID: 21530140554b
Revises: 73378321a73f
Create Date: 2025-01-04 18:33:52.309679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21530140554b'
down_revision = '73378321a73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_organization_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE ')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_organization_id_fkey', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
