"""removed not null constraint dept and level table

Revision ID: 3371577c8cac
Revises: 304dc9e9873a
Create Date: 2025-01-05 21:47:20.581227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3371577c8cac'
down_revision = '304dc9e9873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('departments_organization_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('departments_organization_id_fkey', 'organizations', ['organization_id'], ['id'])
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
