"""added account number column

Revision ID: 3b598d098255
Revises: 00f519d575bb
Create Date: 2025-01-16 16:59:49.382667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b598d098255'
down_revision = '00f519d575bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clearance', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('business_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_column('business_name')
        batch_op.drop_column('account_name')

    with op.batch_alter_table('clearance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
