"""remove fk of wallet from user

Revision ID: 3c84fabe2c0c
Revises: a3dc2bd78cca
Create Date: 2025-01-09 16:35:42.431830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c84fabe2c0c'
down_revision = 'a3dc2bd78cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_wallet_transaction_id_fkey', type_='foreignkey')
        batch_op.drop_column('wallet_transaction_id')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_wallet_transaction_id_fkey', 'wallet_transactions', ['wallet_transaction_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
