"""increase the length of url in the payment tablr

Revision ID: 586426084f56
Revises: 7e69730b6a55
Create Date: 2025-01-12 14:48:15.023599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586426084f56'
down_revision = '7e69730b6a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
