"""converted the default role name in the super admin table from lowercase to uppercase

Revision ID: 73378321a73f
Revises: 54b6c749eda3
Create Date: 2025-01-04 13:08:26.247885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73378321a73f'
down_revision = '54b6c749eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
