"""added some unique constraints to the session table

Revision ID: 7b2976507c17
Revises: e34150234092
Create Date: 2025-01-08 06:41:37.396770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2976507c17'
down_revision = 'e34150234092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_session_per_org', ['name', 'organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_session_per_org', type_='unique')

    # ### end Alembic commands ###
