"""empty message

Revision ID: 7e69730b6a55
Revises: 3c84fabe2c0c
Create Date: 2025-01-12 14:26:48.657895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e69730b6a55'
down_revision = '3c84fabe2c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_wallet_transactions_transaction_reference')

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url')

    op.create_table('wallet_transactions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('transaction_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallet_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallet_transactions_pkey'),
    sa.UniqueConstraint('entity_id', name='wallet_transactions_entity_id_key'),
    sa.UniqueConstraint('id', name='wallet_transactions_id_key')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_transactions_transaction_reference', ['transaction_reference'], unique=True)

    # ### end Alembic commands ###
