"""fixed issue

Revision ID: a7f396e8c13b
Revises: 3b598d098255
Create Date: 2025-01-17 12:03:09.001006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f396e8c13b'
down_revision = '3b598d098255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_charge', sa.Text(), nullable=True))
        batch_op.drop_column('required_documents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_documents', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('percentage_charge')

    # ### end Alembic commands ###
