"""fixed the unique constraint issue in the dept table

Revision ID: c20234e49dab
Revises: 3371577c8cac
Create Date: 2025-01-06 17:43:47.813965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20234e49dab'
down_revision = '3371577c8cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('departments_name_key', type_='unique')
        batch_op.create_unique_constraint('unique_dept_per_org', ['name', 'organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_dept_per_org', type_='unique')
        batch_op.create_unique_constraint('departments_name_key', ['name'])

    # ### end Alembic commands ###
