"""clearance table

Revision ID: cdaa48f6b42f
Revises: 586426084f56
Create Date: 2025-01-15 15:50:18.967625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdaa48f6b42f'
down_revision = '586426084f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearance_certificates',
    sa.Column('certificate_number', sa.String(length=255), nullable=False),
    sa.Column('certificate_path', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('clearance_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clearance_certificates_certificate_number'), ['certificate_number'], unique=True)

    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('clearance_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clearance_certificates_certificate_number'))

    op.drop_table('clearance_certificates')
    # ### end Alembic commands ###
