"""fixed the nullable constraints on the paymentitem table, added the dept relationship

Revision ID: d6f6b0536380
Revises: 7b2976507c17
Create Date: 2025-01-08 17:39:11.112454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f6b0536380'
down_revision = '7b2976507c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.alter_column('academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
