"""added the unique constraint to matric number in the user table

Revision ID: e34150234092
Revises: c20234e49dab
Create Date: 2025-01-07 17:32:18.487956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34150234092'
down_revision = 'c20234e49dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_matric_number')
        batch_op.create_index(batch_op.f('ix_users_matric_number'), ['matric_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_matric_number'))
        batch_op.create_index('ix_users_matric_number', ['matric_number'], unique=False)

    # ### end Alembic commands ###
