"""converted the name column in the role table to an Enum type

Revision ID: e37ea1d9414c
Revises: 290fc303c206
Create Date: 2024-12-31 14:10:52.967378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37ea1d9414c'
down_revision = '290fc303c206'
branch_labels = None
depends_on = None


def upgrade():
    # Create enum type explicitly if it doesn't exist
    role_enum = sa.Enum('ADMIN', 'SUBADMIN', 'BURSAR', 'STUDENT', name='roleenum')
    role_enum.create(op.get_bind(), checkfirst=True)

    # Alter column to use enum with the USING clause to convert data
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column(
            'name',
            existing_type=sa.VARCHAR(length=50),
            type_=role_enum,
            existing_nullable=False,
            postgresql_using="name::roleenum"  # Add the USING clause to cast data
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Enum('ADMIN', 'SUBADMIN', 'BURSAR', 'STUDENT', name='roleenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
